Fix

diff --git a/.github/workflows/01-simple.yaml b/.github/workflows/01-simple.yaml
--- a/.github/workflows/01-simple.yaml
+++ b/.github/workflows/01-simple.yaml
@@ -5,14 +5,14 @@ jobs:
   echo-hello:
     runs-on: ubuntu-latest
     steps:
-      name: "Say hello"
-      run: |
-        echo "Hellow World"  
+      - name: "Say hello"
+        run: |
+          echo "Hellow World"  
 
   say-goodbye:
     runs-on: ubuntu-latest
     steps:
-      name: "Failed step"
-      run: |
-        echo "I will fail"
-        exit 1
+      - name: "Failed step"
+        run: |
+          echo "I will fail"
+          exit 1
